server:
  port: 3030
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-jumpstart-java
  temporal:
    workers:
     -
      task-queue: onboardings
      workflow-classes:
       - your.package.YouWorkflowImpl
      activity-beans:
       - activity-bean-name1
    namespace: temporal-jumpstart-java.sdvdw
    connection:
      target: temporal-jumpstart-java.sdvdw.tmprl.cloud:7233
      mtls:
        key-file: /Users/mnichols/dev/temporal-jumpstart-java/localhost-client-key.pem
        cert-chain-file: /Users/mnichols/dev/temporal-jumpstart-java/localhost-client.pem
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: "${spring.application.name}"
