server:
  port: 3030
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: temporal-curriculum-java
  temporal:
    connection:
      target: local
    workers-auto-discovery:
      packages: null
  curriculum:
    task-queue: onboardings
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: "${spring.application.name}"
